### ISSUE TITLE
[Question] Do we have any callback method on drag end to get the sizes?

### ISSUE THREAD

**Issue by kayesn786** [greggman/react-split-it#1]
Hi,
I really like your work. It's a great library for react.
Just want to know if there's any callback function through which I can get the sizes of each pane.

Or are there any props that am missing?

Thanks

**Comment by greggman** [comment]
Getting the size seems unrelated to this library. For example if you look at [the demos](https://greggman.github.io/react-split-it/), sizing the window will change the sizes of the panes but this library isn't even running any code in that case.

![EKI9juwQRq](https://user-images.githubusercontent.com/234804/105624828-00534900-5e68-11eb-973c-fc35a344c8e7.gif)

This seems to work?

```
function SomeContent(props) {
  const ref = useRef(null);
  const [dims, setDims] = useState({width: 0, height: 0});
  
  useEffect(() => {
    const {width, height} = ref.current.getBoundingClientRect();
  	setDims({width, height});
  });
  
  return (
    <div ref={ref}>
      size: {`${dims.width.toFixed(1)}x${dims.height.toFixed(1)}`}
    </div>
  );
}
```

Example:

https://jsfiddle.net/greggman/pqL043hz/

**Comment by greggman** [comment]
Getting the size seems unrelated to this library. For example if you look at [the demos](https://greggman.github.io/react-split-it/), sizing the window will change the sizes of the panes but this library isn't even running any code in that case.

![EKI9juwQRq](https://user-images.githubusercontent.com/234804/105624828-00534900-5e68-11eb-973c-fc35a344c8e7.gif)

This seems to work?

```
function SomeContent(props) {
  const ref = useRef(null);
  const [dims, setDims] = useState({width: 0, height: 0});
  
  useEffect(() => {
    const {width, height} = ref.current.getBoundingClientRect();
    setTimeout(_ => setDims({width, height}));
  });
  
  return (
    <div ref={ref}>
      size: {`${dims.width.toFixed(1)}x${dims.height.toFixed(1)}`}
    </div>
  );
}
```

Example:

https://jsfiddle.net/greggman/pqL043hz/

**Comment by kayesn786** [comment]
Hi,
I wanted the size (specifically height) of each panes to set Max-size to its inner components so that I get to see a scroll bar when the gutters are moved.

I tried by changing the css property of pane class to overflow: auto.

But that's not the behaviour I wanted. I have a accordion which by default is open. So when I drag the gutter, the contents inside accordion should show scrollbars.

I tried with your above snippet. But the width is changing correctly. The height is same.

https://codesandbox.io/embed/mystifying-bash-rh8hf?codemirror=1

Here I have reproduced it. The height remains same even if I move the gutter.

Please help me if I am wrong.
Thanks

**Comment by kayesn786** [comment]
Figured out that my nested component had issues with scrolling. Had to change the layout. 
Thanks for your help.
